// 単語データ専用ファイル (1-400)
const masterWordList = [
    { id: 1, part: 1, pos: "v", star: 3, en: "follow", ja: ["～の後に続く", "～に従う"], phrase: "follow his advice" },
    { id: 2, part: 1, pos: "v", star: 3, en: "consider", ja: ["～を考慮する"], phrase: "consider the problem" },
    { id: 3, part: 1, pos: "v", star: 2, en: "increase", ja: ["増える", "～を増やす"], phrase: "increase by 20%" },
    { id: 4, part: 1, pos: "v", star: 2, en: "expect", ja: ["～を予期する"], phrase: "expect him to arrive" },
    { id: 5, part: 1, pos: "v", star: 1, en: "decide", ja: ["～することを決意する"], phrase: "decide to go" },
    { id: 6, part: 1, pos: "v", star: 3, en: "develop", ja: ["発達する", "～を発達させる"], phrase: "develop a new theory" },
    { id: 7, part: 1, pos: "v", star: 3, en: "provide", ja: ["～を供給する", "与える"], phrase: "provide him with info" },
    { id: 8, part: 1, pos: "v", star: 1, en: "continue", ja: ["続く", "～を続ける"], phrase: "continue to work" },
    { id: 9, part: 1, pos: "v", star: 2, en: "include", ja: ["～を含む", "含める"], phrase: "include tax" },
    { id: 10, part: 1, pos: "v", star: 3, en: "remain", ja: ["ままでいる"], phrase: "remain silent" },
    { id: 11, part: 1, pos: "v", star: 2, en: "reach", ja: ["～に着く", "～に達する"], phrase: "reach the station" },
    { id: 12, part: 1, pos: "v", star: 3, en: "allow", ja: ["～を許可する"], phrase: "allow him to go" },
    { id: 13, part: 1, pos: "v", star: 3, en: "force", ja: ["～を強制する"], phrase: "force him to work" },
    { id: 14, part: 1, pos: "v", star: 2, en: "offer", ja: ["～を申し出る"], phrase: "offer help" },
    { id: 15, part: 1, pos: "v", star: 3, en: "realize", ja: ["～を悟る"], phrase: "realize the truth" },
    { id: 16, part: 1, pos: "v", star: 3, en: "suggest", ja: ["～と提案する", "～をほのめかす"], phrase: "suggest a new plan" },
    { id: 17, part: 1, pos: "v", star: 3, en: "require", ja: ["～を必要とする"], phrase: "require attention" },
    { id: 18, part: 1, pos: "v", star: 1, en: "worry", ja: ["心配する"], phrase: "worry about the future" },
    { id: 19, part: 1, pos: "v", star: 2, en: "wonder", ja: ["～かと疑問に思う"], phrase: "wonder why" },
    { id: 20, part: 1, pos: "v", star: 3, en: "cost", ja: ["～を要する"], phrase: "cost 100 dollars" },
    { id: 21, part: 1, pos: "v", star: 2, en: "tend", ja: ["～する傾向がある", "～しがちである"], phrase: "tend to forget" },
    { id: 22, part: 1, pos: "v", star: 3, en: "depend", ja: ["～に依存する", "～しだいで決まる"], phrase: "depend on the weather" },
    { id: 23, part: 1, pos: "v", star: 1, en: "share", ja: ["～を分け合う", "共有する"], phrase: "share a room" },
    { id: 24, part: 1, pos: "v", star: 3, en: "demand", ja: ["～を要求する"], phrase: "demand an apology" },
    { id: 25, part: 1, pos: "v", star: 1, en: "support", ja: ["～を支持する"], phrase: "support the idea" },
    { id: 26, part: 1, pos: "v", star: 1, en: "hire", ja: ["～を雇う"], phrase: "hire a lawyer" },
    { id: 27, part: 1, pos: "v", star: 3, en: "regard", hint: "A as B", ja: ["AをBだと思う", "みなす"], phrase: "regard A as B" },
    { id: 28, part: 1, pos: "v", star: 2, en: "base", hint: "A on B", ja: ["AがBに基づいている"], phrase: "be based on facts" },
    { id: 29, part: 1, pos: "v", star: 2, en: "improve", ja: ["～を向上させる"], phrase: "improve the quality" },
    { id: 30, part: 1, pos: "v", star: 3, en: "recognize", ja: ["～を認める"], phrase: "recognize the importance" },
    { id: 31, part: 1, pos: "v", star: 2, en: "notice", ja: ["～に気づく"], phrase: "notice the change" },
    { id: 32, part: 1, pos: "v", star: 3, en: "suppose", ja: ["～だと思う"], phrase: "suppose that..." },
    { id: 33, part: 1, pos: "v", star: 3, en: "raise", ja: ["～を上げる", "～を育てる"], phrase: "raise children" },
    { id: 34, part: 1, pos: "v", star: 2, en: "prefer", ja: ["～をより好む"], phrase: "prefer tea to coffee" },
    { id: 35, part: 1, pos: "v", star: 1, en: "cheer", ja: ["～を励ます"], phrase: "cheer him up" },
    { id: 36, part: 1, pos: "v", star: 3, en: "suffer", ja: ["～を経験する", "受ける", "苦しむ"], phrase: "suffer from cancer" },
    { id: 37, part: 1, pos: "v", star: 3, en: "describe", ja: ["～を描写する", "～の特徴を説明する"], phrase: "describe the scene" },
    { id: 38, part: 1, pos: "v", star: 3, en: "prevent", ja: ["～をさまたげる"], phrase: "prevent him from going" },
    { id: 39, part: 1, pos: "v", star: 2, en: "reduce", ja: ["～を減らす"], phrase: "reduce costs" },
    { id: 40, part: 1, pos: "v", star: 2, en: "mistake", hint: "A for B", ja: ["～を誤解する", "AをBとまちがえる"], phrase: "mistake A for B" },
    { id: 41, part: 1, pos: "v", star: 2, en: "prepare", ja: ["～の準備をする"], phrase: "prepare for the exam" },
    { id: 42, part: 1, pos: "v", star: 3, en: "encourage", ja: ["はげます"], phrase: "encourage him to try" },
    { id: 43, part: 1, pos: "v", star: 3, en: "prove", ja: ["～だとわかる"], phrase: "prove to be true" },
    { id: 44, part: 1, pos: "v", star: 3, en: "treat", ja: ["～をあつかう"], phrase: "treat him kindly" },
    { id: 45, part: 1, pos: "v", star: 3, en: "establish", ja: ["～を設立する", "創立する"], phrase: "establish a company" },
    { id: 46, part: 1, pos: "v", star: 3, en: "relate", ja: ["関係がある"], phrase: "be related to..." },
    { id: 47, part: 1, pos: "v", star: 3, en: "compare", hint: "A with B", ja: ["AとBを比較する", "AをBにたとえる"], phrase: "compare A with B" },
    { id: 48, part: 1, pos: "v", star: 2, en: "spread", ja: ["～を広げる", "広がる"], phrase: "spread the rumor" },
    { id: 49, part: 1, pos: "v", star: 3, en: "refer", ja: ["～を指示する"], phrase: "refer to the book" },
    { id: 50, part: 1, pos: "v", star: 2, en: "supply", ja: ["～を供給する"], phrase: "supply them with food" },
    { id: 51, part: 1, pos: "v", star: 2, en: "gain", ja: ["～を得る"], phrase: "gain knowledge" },
    { id: 52, part: 1, pos: "v", star: 2, en: "destroy", ja: ["～を破壊する"], phrase: "destroy the building" },
    { id: 53, part: 1, pos: "v", star: 3, en: "apply", ja: ["当てはまる", "申し込む"], phrase: "apply to the case" },
    { id: 54, part: 1, pos: "v", star: 2, en: "seek", ja: ["～を求める"], phrase: "seek advice" },
    { id: 55, part: 1, pos: "v", star: 1, en: "search", ja: ["～を捜す"], phrase: "search for the key" },
    { id: 56, part: 1, pos: "v", star: 3, en: "claim", ja: ["～と主張する"], phrase: "claim that..." },
    { id: 57, part: 1, pos: "v", star: 3, en: "draw", ja: ["～を引っぱる"], phrase: "draw a conclusion" },
    { id: 58, part: 1, pos: "v", star: 2, en: "refuse", ja: ["～を断る"], phrase: "refuse to answer" },
    { id: 59, part: 1, pos: "v", star: 2, en: "respond", ja: ["～に返答する"], phrase: "respond to the question" },
    { id: 60, part: 1, pos: "v", star: 2, en: "mention", ja: ["～について述べる"], phrase: "mention the fact" },
    { id: 61, part: 1, pos: "v", star: 2, en: "judge", ja: ["～を判断する"], phrase: "judge by appearance" },
    { id: 62, part: 1, pos: "v", star: 3, en: "approach", ja: ["～に接近する", "～に取り組む", "方法"], phrase: "approach the problem" },
    { id: 63, part: 1, pos: "v", star: 3, en: "admit", ja: ["～を認める"], phrase: "admit your mistake" },
    { id: 64, part: 1, pos: "v", star: 3, en: "reflect", ja: ["～を反映する", "～を反射する"], phrase: "reflect the reality" },
    { id: 65, part: 1, pos: "v", star: 3, en: "perform", ja: ["～を行う", "～を遂行する"], phrase: "perform a task" },
    { id: 66, part: 1, pos: "v", star: 1, en: "bore", ja: ["～をうんざりさせる"], phrase: "bore me to death" },
    { id: 67, part: 1, pos: "v", star: 2, en: "survive", ja: ["生き残る"], phrase: "survive the war" },
    { id: 68, part: 1, pos: "v", star: 3, en: "represent", ja: ["～を表す"], phrase: "represent the company" },
    { id: 69, part: 1, pos: "v", star: 3, en: "argue", ja: ["～と主張する"], phrase: "argue that..." },
    { id: 70, part: 1, pos: "v", star: 3, en: "grant", ja: ["～を認める", "～を与える"], phrase: "take it for granted" },
    { id: 71, part: 1, pos: "v", star: 3, en: "indicate", ja: ["～を指し示す"], phrase: "indicate the fact" },
    { id: 72, part: 1, pos: "v", star: 2, en: "belong", ja: ["所属している"], phrase: "belong to the club" },
    { id: 73, part: 1, pos: "v", star: 3, en: "acquire", ja: ["～を習得する"], phrase: "acquire language" },
    { id: 74, part: 1, pos: "v", star: 1, en: "reply", ja: ["返事をする"], phrase: "reply to the letter" },
    { id: 75, part: 1, pos: "v", star: 2, en: "feed", ja: ["～にエサをやる"], phrase: "feed the dog" },
    { id: 76, part: 1, pos: "v", star: 2, en: "escape", ja: ["逃げる"], phrase: "escape from danger" },
    { id: 77, part: 1, pos: "v", star: 3, en: "replace", hint: "A with B", ja: ["Aに取って代わる", "AをBと取り替える"], phrase: "replace A with B" },
    { id: 78, part: 1, pos: "v", star: 3, en: "reveal", ja: ["～を明らかにする"], phrase: "reveal the secret" },
    { id: 79, part: 1, pos: "v", star: 2, en: "surround", ja: ["～を取り囲む"], phrase: "surround the house" },
    { id: 80, part: 1, pos: "v", star: 2, en: "suit", ja: ["～に合う"], phrase: "suit your taste" },
    { id: 81, part: 1, pos: "v", star: 3, en: "estimate", ja: ["～を推定する"], phrase: "estimate the cost" },
    { id: 82, part: 1, pos: "v", star: 2, en: "aim", ja: ["～をねらう"], phrase: "aim at the target" },
    { id: 83, part: 1, pos: "v", star: 2, en: "earn", ja: ["～をもうける", "かせぐ"], phrase: "earn money" },
    { id: 84, part: 1, pos: "v", star: 3, en: "decline", ja: ["衰退する", "低下する", "～を辞退する"], phrase: "decline the offer" },
    { id: 85, part: 1, pos: "v", star: 3, en: "afford", ja: ["～をする余裕がある"], phrase: "can afford to buy" },
    { id: 86, part: 1, pos: "v", star: 2, en: "confuse", hint: "A with B", ja: ["～を当惑させる", "AをBと混同する"], phrase: "confuse A with B" },
    { id: 87, part: 1, pos: "v", star: 1, en: "graduate", ja: ["～を卒業する"], phrase: "graduate from college" },
    { id: 88, part: 1, pos: "v", star: 3, en: "vary", ja: ["変わる", "さまざまである"], phrase: "vary from country to country" },
    { id: 89, part: 1, pos: "v", star: 2, en: "remove", ja: ["～を移す", "取り去る"], phrase: "remove the dirt" },
    { id: 90, part: 1, pos: "v", star: 3, en: "insist", ja: ["～と主張する", "言い張る"], phrase: "insist on going" },
    { id: 91, part: 1, pos: "v", star: 3, en: "examine", ja: ["～を調査する"], phrase: "examine the body" },
    { id: 92, part: 1, pos: "v", star: 2, en: "remind", hint: "A of B", ja: ["ＡにＢを思い出させる"], phrase: "remind A of B" },
    { id: 93, part: 1, pos: "v", star: 3, en: "contribute", ja: ["～に貢献する", "～の一因となる", "寄付する"], phrase: "contribute to society" },
    { id: 94, part: 1, pos: "v", star: 2, en: "warn", ja: ["～に警告する"], phrase: "warn him of danger" },
    { id: 95, part: 1, pos: "v", star: 1, en: "connect", ja: ["～をつなぐ"], phrase: "connect to the Internet" },
    { id: 96, part: 1, pos: "v", star: 2, en: "match", ja: ["～に匹敵する", "～に調和する"], phrase: "match your shirt" },
    { id: 97, part: 1, pos: "v", star: 2, en: "focus", ja: ["焦点を合わせる"], phrase: "focus on the issue" },
    { id: 98, part: 1, pos: "v", star: 3, en: "reject", ja: ["～を断る"], phrase: "reject the proposal" },
    { id: 99, part: 1, pos: "v", star: 3, en: "convince", ja: ["～を納得させる", "確信させる"], phrase: "convince him of the fact" },
    { id: 100, part: 1, pos: "v", star: 3, en: "associate", hint: "A with B", ja: ["AをBに関連づける", "AからBを連想する"], phrase: "associate A with B" },
    { id: 101, part: 1, pos: "v", star: 2, en: "rush", ja: ["急いで行く"], phrase: "rush to the hospital" },
    { id: 102, part: 1, pos: "v", star: 2, en: "stress", ja: ["～を強調する"], phrase: "stress the importance" },
    { id: 103, part: 1, pos: "v", star: 3, en: "attract", ja: ["～を引きつける"], phrase: "attract attention" },
    { id: 104, part: 1, pos: "v", star: 3, en: "rely", hint: "on A", ja: ["Aに頼る"], phrase: "rely on him" },
    { id: 105, part: 1, pos: "v", star: 2, en: "regret", ja: ["～を後悔する"], phrase: "regret doing" },
    { id: 106, part: 1, pos: "v", star: 3, en: "adopt", ja: ["～を採用する"], phrase: "adopt a new method" },
    { id: 107, part: 1, pos: "v", star: 1, en: "shake", ja: ["～を振る"], phrase: "shake hands" },
    { id: 108, part: 1, pos: "v", star: 2, en: "hurt", ja: ["～を傷つける"], phrase: "hurt my feelings" },
    { id: 109, part: 1, pos: "v", star: 3, en: "operate", ja: ["作動する", "～を操作する", "手術する"], phrase: "operate the machine" },
    { id: 110, part: 1, pos: "v", star: 3, en: "extend", ja: ["～を広げる", "延長する"], phrase: "extend the deadline" },
    { id: 111, part: 1, pos: "v", star: 3, en: "blame", hint: "A for B", ja: ["～を非難する", "AをBのせいにする"], phrase: "blame A for B" },
    { id: 112, part: 1, pos: "v", star: 3, en: "consist", hint: "of A", ja: ["Aで構成されている"], phrase: "consist of members" },
    { id: 113, part: 1, pos: "v", star: 3, en: "persuade", ja: ["～を説得する"], phrase: "persuade him to go" },
    { id: 114, part: 1, pos: "v", star: 2, en: "admire", ja: ["～に感心する"], phrase: "admire her courage" },
    { id: 115, part: 1, pos: "v", star: 2, en: "disappoint", ja: ["～を失望させる"], phrase: "be disappointed at" },
    { id: 116, part: 1, pos: "v", star: 3, en: "expand", ja: ["拡大する"], phrase: "expand the business" },
    { id: 117, part: 1, pos: "v", star: 3, en: "preserve", ja: ["～を保護する"], phrase: "preserve nature" },
    { id: 118, part: 1, pos: "v", star: 3, en: "struggle", ja: ["苦闘する", "もがく"], phrase: "struggle to survive" },
    { id: 119, part: 1, pos: "v", star: 2, en: "arrange", ja: ["～の手はずを整える", "～を配列する"], phrase: "arrange a meeting" },
    { id: 120, part: 1, pos: "v", star: 2, en: "disturb", ja: ["～を妨げる"], phrase: "disturb his sleep" },
    { id: 121, part: 1, pos: "v", star: 2, en: "employ", ja: ["～を雇う", "～を用いる"], phrase: "employ a new system" },
    { id: 122, part: 1, pos: "v", star: 3, en: "engage", hint: "in A", ja: ["Aに従事する", "Aを行う"], phrase: "engage in activities" },
    { id: 123, part: 1, pos: "v", star: 3, en: "abandon", ja: ["～を捨てる"], phrase: "abandon the plan" },
    { id: 124, part: 1, pos: "v", star: 2, en: "display", ja: ["～を展示する", "～を表す"], phrase: "display talent" },
    { id: 125, part: 1, pos: "v", star: 3, en: "encounter", ja: ["～に偶然出会う"], phrase: "encounter a problem" },
    { id: 126, part: 1, pos: "v", star: 2, en: "amuse", ja: ["～を楽しませる"], phrase: "amuse the children" },
    { id: 127, part: 1, pos: "v", star: 2, en: "bother", ja: ["～に面倒をかける", "困らせる"], phrase: "bother to do" },
    { id: 128, part: 1, pos: "v", star: 3, en: "concentrate", ja: ["集中する"], phrase: "concentrate on study" },
    { id: 129, part: 1, pos: "v", star: 3, en: "adapt", ja: ["～を適応させる", "適応する"], phrase: "adapt to the environment" },
    { id: 130, part: 1, pos: "v", star: 2, en: "puzzle", ja: ["～を当惑させる"], phrase: "puzzle the experts" },
    { id: 131, part: 1, pos: "v", star: 3, en: "appeal", hint: "to A", ja: ["Aに訴える", "Aを引きつける"], phrase: "appeal to the public" },
    { id: 132, part: 1, pos: "v", star: 2, en: "combine", hint: "A with B", ja: ["AをBと結合させる"], phrase: "combine A with B" },
    { id: 133, part: 1, pos: "v", star: 2, en: "delay", ja: ["～を遅らせる"], phrase: "delay the flight" },
    { id: 134, part: 1, pos: "v", star: 1, en: "repair", ja: ["～を修理する"], phrase: "repair the car" },
    { id: 135, part: 1, pos: "v", star: 3, en: "fascinate", ja: ["～を夢中にさせる"], phrase: "be fascinated by" },
    { id: 136, part: 1, pos: "v", star: 1, en: "pardon", ja: ["～を許す"], phrase: "beg your pardon" },
    { id: 137, part: 1, pos: "v", star: 2, en: "import", ja: ["～を輸入する"], phrase: "import goods" },
    { id: 138, part: 1, pos: "v", star: 3, en: "remark", ja: ["述べる"], phrase: "remark that..." },
    { id: 139, part: 1, pos: "v", star: 2, en: "reserve", ja: ["～を予約する", "～を取っておく"], phrase: "reserve a room" },
    { id: 140, part: 1, pos: "v", star: 2, en: "amaze", ja: ["～を驚嘆させる"], phrase: "amaze the audience" },
    { id: 141, part: 1, pos: "v", star: 2, en: "frighten", ja: ["～をおびえさせる"], phrase: "frighten the child" },
    { id: 142, part: 1, pos: "v", star: 3, en: "release", ja: ["～を解放する", "～を発表する"], phrase: "release the prisoner" },
    { id: 143, part: 1, pos: "v", star: 1, en: "rent", ja: ["～を賃借りする"], phrase: "rent an apartment" },
    { id: 144, part: 1, pos: "v", star: 2, en: "recover", hint: "from A", ja: ["Aから回復する"], phrase: "recover from illness" },
    { id: 145, part: 1, pos: "v", star: 3, en: "suspect", hint: "A of B", ja: ["～ではないかと思う", "AにBの疑いをかける"], phrase: "suspect him of..." },
    { id: 146, part: 1, pos: "v", star: 2, en: "deliver", ja: ["～を配達する", "渡す", "～をする"], phrase: "deliver a speech" },
    { id: 147, part: 1, pos: "v", star: 3, en: "identify", hint: "with A", ja: ["～の正体をつきとめる", "Aと共感する"], phrase: "identify the body" },
    { id: 148, part: 1, pos: "v", star: 3, en: "locate", ja: ["位置する"], phrase: "be located in" },
    { id: 149, part: 1, pos: "v", star: 2, en: "manufacture", ja: ["～を製造する"], phrase: "manufacture cars" },
    { id: 150, part: 1, pos: "v", star: 3, en: "occupy", ja: ["～を占める"], phrase: "occupy the space" },
    { id: 151, part: 1, pos: "v", star: 2, en: "own", ja: ["～を所有している"], phrase: "own a house" },
    { id: 152, part: 1, pos: "v", star: 3, en: "expose", hint: "A to B", ja: ["ＡをＢにさらす"], phrase: "expose A to B" },
    { id: 153, part: 1, pos: "v", star: 2, en: "translate", hint: "A into B", ja: ["AをBに翻訳する"], phrase: "translate A into B" },
    { id: 154, part: 1, pos: "v", star: 2, en: "cure", hint: "A of B", ja: ["AのBを治療する"], phrase: "cure him of..." },
    { id: 155, part: 1, pos: "v", star: 3, en: "perceive", ja: ["～を知覚する"], phrase: "perceive the danger" },
    { id: 156, part: 1, pos: "v", star: 3, en: "adjust", ja: ["～に慣れる", "調節して合わせる"], phrase: "adjust to the change" },
    { id: 157, part: 1, pos: "v", star: 2, en: "alarm", ja: ["～をぎょっとさせる", "おびえさせる"], phrase: "be alarmed at" },
    { id: 158, part: 1, pos: "v", star: 2, en: "assist", hint: "A in doing", ja: ["～を助ける", "Aが～するのを手伝う"], phrase: "assist him in doing" },
    { id: 159, part: 1, pos: "v", star: 1, en: "freeze", ja: ["凍りつく"], phrase: "freeze to death" },
    { id: 160, part: 1, pos: "v", star: 2, en: "spoil", ja: ["～を台無しにする"], phrase: "spoil the party" },
    { id: 161, part: 1, pos: "v", star: 2, en: "shift", ja: ["～を変える"], phrase: "shift the focus" },
    { id: 162, part: 1, pos: "v", star: 2, en: "embarrass", ja: ["～を困惑させる", "～に恥ずかしい思いをさせる"], phrase: "embarrass her" },
    { id: 163, part: 1, pos: "v", star: 3, en: "approve", ja: ["賛成する", "～を承認する"], phrase: "approve of the plan" },
    { id: 164, part: 1, pos: "v", star: 2, en: "weigh", ja: ["～の重さがある", "～を比較検討する", "よく考える"], phrase: "weigh 50 kilos" },
    { id: 165, part: 1, pos: "v", star: 2, en: "stretch", ja: ["～を広げる"], phrase: "stretch the legs" },
    { id: 166, part: 1, pos: "v", star: 3, en: "participate", hint: "in A", ja: ["Aに参加する"], phrase: "participate in..." },
    { id: 167, part: 1, pos: "v", star: 2, en: "exhibit", ja: ["～を展示する"], phrase: "exhibit paintings" },
    { id: 168, part: 1, pos: "v", star: 3, en: "owe", hint: "A to B", ja: ["AのことはBのおかげだ"], phrase: "owe my success to" },
    { id: 169, part: 1, pos: "v", star: 2, en: "celebrate", ja: ["～を祝う"], phrase: "celebrate the birthday" },
    { id: 170, part: 1, pos: "v", star: 1, en: "decorate", ja: ["～を装飾する"], phrase: "decorate the room" },
    { id: 171, part: 1, pos: "v", star: 2, en: "forgive", hint: "A for B", ja: ["AのBを許す"], phrase: "forgive him for" },
    { id: 172, part: 1, pos: "v", star: 1, en: "seat", ja: ["座っている"], phrase: "be seated" },
    { id: 173, part: 1, pos: "v", star: 2, en: "injure", ja: ["～を傷つける"], phrase: "be injured in" },
    { id: 174, part: 1, pos: "v", star: 1, en: "sew", ja: ["～を縫う"], phrase: "sew a dress" },
    { id: 175, part: 1, pos: "n", star: 3, en: "result", ja: ["結果"], phrase: "as a result" },
    { id: 176, part: 1, pos: "n", star: 3, en: "feature", ja: ["特徴"], phrase: "a main feature" },
    { id: 177, part: 1, pos: "n", star: 3, en: "society", ja: ["社会", "協会", "団体"], phrase: "modern society" },
    { id: 178, part: 1, pos: "n", star: 1, en: "wheel", ja: ["車輪", "ハンドル"], phrase: "at the wheel" },
    { id: 179, part: 1, pos: "n", star: 3, en: "value", ja: ["価値"], phrase: "the value of education" },
    { id: 180, part: 1, pos: "n", star: 3, en: "effect", ja: ["効果", "影響", "結果"], phrase: "have an effect on" },
    { id: 181, part: 1, pos: "n", star: 3, en: "individual", ja: ["個人"], phrase: "an individual" },
    { id: 182, part: 1, pos: "n", star: 3, en: "influence", ja: ["影響"], phrase: "have an influence on" },
    { id: 183, part: 1, pos: "n", star: 2, en: "fee", ja: ["謝礼", "料金"], phrase: "pay the fee" },
    { id: 184, part: 1, pos: "n", star: 3, en: "rate", ja: ["割合", "速度"], phrase: "at a high rate" },
    { id: 185, part: 1, pos: "n", star: 2, en: "sign", ja: ["印", "兆候"], phrase: "a sign of spring" },
    { id: 186, part: 1, pos: "n", star: 2, en: "service", ja: ["公共事業", "業務"], phrase: "public service" },
    { id: 187, part: 1, pos: "n", star: 3, en: "advance", ja: ["前進", "進歩"], phrase: "in advance" },
    { id: 188, part: 1, pos: "n", star: 1, en: "laughter", ja: ["笑い"], phrase: "burst into laughter" },
    { id: 189, part: 1, pos: "n", star: 3, en: "material", ja: ["物質"], phrase: "raw material" },
    { id: 190, part: 1, pos: "n", star: 2, en: "industry", ja: ["工業"], phrase: "the auto industry" },
    { id: 191, part: 1, pos: "n", star: 3, en: "attempt", ja: ["試み"], phrase: "an attempt to do" },
    { id: 192, part: 1, pos: "n", star: 2, en: "trade", ja: ["貿易"], phrase: "foreign trade" },
    { id: 193, part: 1, pos: "n", star: 3, en: "progress", ja: ["進歩", "前進"], phrase: "make progress" },
    { id: 194, part: 1, pos: "n", star: 2, en: "excuse", ja: ["言い訳"], phrase: "make an excuse" },
    { id: 195, part: 1, pos: "n", star: 2, en: "custom", ja: ["習慣", "税関"], phrase: "social custom" },
    { id: 196, part: 1, pos: "n", star: 3, en: "passage", ja: ["一節", "経過", "通行"], phrase: "read the passage" },
    { id: 197, part: 1, pos: "n", star: 3, en: "economy", ja: ["経済"], phrase: "the global economy" },
    { id: 198, part: 1, pos: "n", star: 2, en: "track", ja: ["小道", "足跡"], phrase: "keep track of" },
    { id: 199, part: 1, pos: "n", star: 2, en: "transportation", ja: ["交通機関", "輸送"], phrase: "public transportation" },
    { id: 200, part: 1, pos: "n", star: 2, en: "official", ja: ["役人"], phrase: "a government official" },
    { id: 201, part: 1, pos: "n", star: 3, en: "sight", ja: ["見ること", "光景", "視力"], phrase: "at first sight" },
    { id: 202, part: 1, pos: "n", star: 3, en: "taste", ja: ["味", "好み"], phrase: "a taste for music" },
    { id: 203, part: 1, pos: "n", star: 2, en: "range", ja: ["範囲"], phrase: "a wide range of" },
    { id: 204, part: 1, pos: "n", star: 2, en: "appointment", ja: ["約束", "予約"], phrase: "make an appointment" },
    { id: 205, part: 1, pos: "n", star: 3, en: "patient", ja: ["患者", "忍耐強い"], phrase: "a cancer patient" },
    { id: 206, part: 1, pos: "n", star: 2, en: "project", ja: ["計画"], phrase: "a research project" },
    { id: 207, part: 1, pos: "n", star: 2, en: "favor", ja: ["好意"], phrase: "do me a favor" },
    { id: 208, part: 1, pos: "n", star: 3, en: "appearance", ja: ["外見", "様子", "出現"], phrase: "judge by appearance" },
    { id: 209, part: 1, pos: "n", star: 3, en: "risk", ja: ["危険"], phrase: "take a risk" },
    { id: 210, part: 1, pos: "n", star: 3, en: "benefit", ja: ["利益"], phrase: "benefit from it" },
    { id: 211, part: 1, pos: "n", star: 2, en: "resident", ja: ["住民"], phrase: "local residents" },
    { id: 212, part: 1, pos: "n", star: 2, en: "relative", ja: ["親族", "親戚"], phrase: "a close relative" },
    { id: 213, part: 1, pos: "n", star: 3, en: "region", ja: ["地域"], phrase: "in the region" },
    { id: 214, part: 1, pos: "n", star: 3, en: "characteristic", ja: ["特徴"], phrase: "a characteristic feature" },
    { id: 215, part: 1, pos: "n", star: 3, en: "pain", ja: ["苦痛"], phrase: "feel pain" },
    { id: 216, part: 1, pos: "n", star: 1, en: "twin", ja: ["双子の一方", "双生児"], phrase: "identical twins" },
    { id: 217, part: 1, pos: "n", star: 3, en: "occasion", ja: ["場合", "機会"], phrase: "on this occasion" },
    { id: 218, part: 1, pos: "n", star: 3, en: "principle", ja: ["原理", "原則"], phrase: "the principle of" },
    { id: 219, part: 1, pos: "n", star: 2, en: "department", ja: ["部門", "学科"], phrase: "the sales department" },
    { id: 220, part: 1, pos: "n", star: 2, en: "duty", ja: ["義務", "関税"], phrase: "sense of duty" },
    { id: 221, part: 1, pos: "n", star: 3, en: "scene", ja: ["場面", "現場"], phrase: "the scene of the accident" },
    { id: 222, part: 1, pos: "n", star: 1, en: "jam", ja: ["渋滞"], phrase: "traffic jam" },
    { id: 223, part: 1, pos: "n", star: 3, en: "spirit", ja: ["精神"], phrase: "team spirit" },
    { id: 224, part: 1, pos: "n", star: 3, en: "medium", ja: ["手段"], phrase: "a medium of communication" },
    { id: 225, part: 1, pos: "n", star: 2, en: "mass", ja: ["一般大衆", "多くの"], phrase: "the masses" },
    { id: 226, part: 1, pos: "n", star: 3, en: "audience", ja: ["聴衆", "観客"], phrase: "a large audience" },
    { id: 227, part: 1, pos: "n", star: 2, en: "element", ja: ["要素", "元素"], phrase: "an essential element" },
    { id: 228, part: 1, pos: "n", star: 3, en: "climate", ja: ["気候"], phrase: "global climate" },
    { id: 229, part: 1, pos: "n", star: 3, en: "revolution", ja: ["革命"], phrase: "industrial revolution" },
    { id: 230, part: 1, pos: "n", star: 2, en: "quarter", ja: ["4分の1"], phrase: "three quarters" },
    { id: 231, part: 1, pos: "n", star: 1, en: "furniture", ja: ["家具"], phrase: "a piece of furniture" },
    { id: 232, part: 1, pos: "n", star: 3, en: "brain", ja: ["脳"], phrase: "human brain" },
    { id: 233, part: 1, pos: "n", star: 3, en: "atmosphere", ja: ["大気", "雰囲気"], phrase: "friendly atmosphere" },
    { id: 234, part: 1, pos: "n", star: 3, en: "property", ja: ["財産"], phrase: "private property" },
    { id: 235, part: 1, pos: "n", star: 2, en: "reward", ja: ["報酬"], phrase: "as a reward" },
    { id: 236, part: 1, pos: "n", star: 2, en: "security", ja: ["安全"], phrase: "national security" },
    { id: 237, part: 1, pos: "n", star: 2, en: "delight", ja: ["大喜び"], phrase: "to my delight" },
    { id: 238, part: 1, pos: "n", star: 2, en: "desert", ja: ["砂漠"], phrase: "in the desert" },
    { id: 239, part: 1, pos: "n", star: 2, en: "background", ja: ["背景", "生い立ち", "経歴"], phrase: "family background" },
    { id: 240, part: 1, pos: "n", star: 2, en: "trend", ja: ["傾向"], phrase: "recent trend" },
    { id: 241, part: 1, pos: "n", star: 2, en: "vote", ja: ["投票"], phrase: "cast a vote" },
    { id: 242, part: 1, pos: "n", star: 3, en: "impact", hint: "on A", ja: ["Aへの影響", "衝撃"], phrase: "impact on society" },
    { id: 243, part: 1, pos: "n", star: 3, en: "institution", ja: ["機関", "制度"], phrase: "educational institution" },
    { id: 244, part: 1, pos: "n", star: 3, en: "interaction", hint: "with A", ja: ["Aとの交流"], phrase: "interaction with others" },
    { id: 245, part: 1, pos: "n", star: 3, en: "alternative", ja: ["代わりのもの"], phrase: "have no alternative" },
    { id: 246, part: 1, pos: "n", star: 3, en: "harm", ja: ["害"], phrase: "do more harm than good" },
    { id: 247, part: 1, pos: "n", star: 2, en: "agency", ja: ["機関", "代理店"], phrase: "advertising agency" },
    { id: 248, part: 1, pos: "n", star: 3, en: "capacity", ja: ["能力"], phrase: "intellectual capacity" },
    { id: 249, part: 1, pos: "n", star: 2, en: "minister", ja: ["大臣"], phrase: "prime minister" },
    { id: 250, part: 1, pos: "n", star: 1, en: "volunteer", ja: ["ボランティア"], phrase: "a volunteer group" },
    { id: 251, part: 1, pos: "n", star: 3, en: "access", hint: "to A", ja: ["Aを利用する権利"], phrase: "have access to information" },
    { id: 252, part: 1, pos: "n", star: 2, en: "quantity", ja: ["量"], phrase: "quality and quantity" },
    { id: 253, part: 1, pos: "n", star: 2, en: "branch", ja: ["枝", "支店", "部門"], phrase: "a local branch" },
    { id: 254, part: 1, pos: "a", star: 3, en: "common", ja: ["共通の", "普通の"], phrase: "common sense" },
    { id: 255, part: 1, pos: "a", star: 2, en: "rough", ja: ["荒い", "大雑把な"], phrase: "a rough sketch" },
    { id: 256, part: 1, pos: "a", star: 3, en: "likely", hint: "to do", ja: ["～する可能性が高い", "ありそうな"], phrase: "be likely to happen" },
    { id: 257, part: 1, pos: "a", star: 3, en: "serious", ja: ["深刻な"], phrase: "a serious problem" },
    { id: 258, part: 1, pos: "a", star: 3, en: "particular", ja: ["ある特定の", "特有の"], phrase: "in particular" },
    { id: 259, part: 1, pos: "a", star: 3, en: "available", ja: ["手に入る", "利用できる"], phrase: "available information" },
    { id: 260, part: 1, pos: "a", star: 1, en: "bilingual", ja: ["二言語使用の"], phrase: "a bilingual speaker" },
    { id: 261, part: 1, pos: "a", star: 2, en: "ready", hint: "for A", ja: ["Aの用意ができた"], phrase: "get ready for school" },
    { id: 262, part: 1, pos: "a", star: 2, en: "correct", ja: ["正しい"], phrase: "the correct answer" },
    { id: 263, part: 1, pos: "a", star: 3, en: "familiar", hint: "with A", ja: ["Aを熟知している", "詳しい"], phrase: "be familiar with the city" },
    { id: 264, part: 1, pos: "a", star: 3, en: "physical", ja: ["身体の", "肉体の"], phrase: "physical exercise" },
    { id: 265, part: 1, pos: "a", star: 3, en: "worth", hint: "doing", ja: ["～する価値がある"], phrase: "be worth reading" },
    { id: 266, part: 1, pos: "a", star: 3, en: "involved", hint: "in A", ja: ["Aに関係している", "参加している"], phrase: "be involved in the project" },
    { id: 267, part: 1, pos: "a", star: 2, en: "fantastic", ja: ["すばらしい"], phrase: "a fantastic experience" },
    { id: 268, part: 1, pos: "a", star: 3, en: "private", ja: ["個人の", "私的な"], phrase: "private life" },
    { id: 269, part: 1, pos: "a", star: 3, en: "obvious", ja: ["明白な"], phrase: "it is obvious that..." },
    { id: 270, part: 1, pos: "a", star: 3, en: "native", ja: ["母国の"], phrase: "native language" },
    { id: 271, part: 1, pos: "a", star: 3, en: "complex", ja: ["複雑な"], phrase: "a complex system" },
    { id: 272, part: 1, pos: "a", star: 2, en: "willing", hint: "to do", ja: ["～する気がある", "かまわない"], phrase: "be willing to help" },
    { id: 273, part: 1, pos: "a", star: 3, en: "current", ja: ["最新の"], phrase: "the current situation" },
    { id: 274, part: 1, pos: "a", star: 2, en: "male", ja: ["男の"], phrase: "a male student" },
    { id: 275, part: 1, pos: "a", star: 3, en: "proper", ja: ["適切な"], phrase: "the proper way" },
    { id: 276, part: 1, pos: "a", star: 3, en: "capable", hint: "of doing", ja: ["～する能力がある"], phrase: "be capable of winning" },
    { id: 277, part: 1, pos: "a", star: 3, en: "independent", hint: "of A", ja: ["Aから独立した"], phrase: "be independent of parents" },
    { id: 278, part: 1, pos: "a", star: 2, en: "positive", ja: ["積極的な"], phrase: "positive thinking" },
    { id: 279, part: 1, pos: "a", star: 2, en: "pleasant", ja: ["楽しい"], phrase: "a pleasant memory" },
    { id: 280, part: 1, pos: "a", star: 3, en: "significant", ja: ["重要な"], phrase: "a significant change" },
    { id: 281, part: 1, pos: "a", star: 2, en: "former", ja: ["前の"], phrase: "the former president" },
    { id: 282, part: 1, pos: "a", star: 2, en: "chemical", ja: ["化学的な"], phrase: "a chemical reaction" },
    { id: 283, part: 1, pos: "a", star: 2, en: "upset", ja: ["動揺している"], phrase: "be upset by the news" },
    { id: 284, part: 1, pos: "a", star: 3, en: "previous", ja: ["前の"], phrase: "previous experience" },
    { id: 285, part: 1, pos: "a", star: 2, en: "calm", ja: ["冷静な"], phrase: "keep calm" },
    { id: 286, part: 1, pos: "a", star: 3, en: "specific", ja: ["特定の"], phrase: "a specific purpose" },
    { id: 287, part: 1, pos: "a", star: 3, en: "conscious", hint: "of A", ja: ["Aを意識している"], phrase: "be conscious of danger" },
    { id: 288, part: 1, pos: "a", star: 3, en: "superior", hint: "to A", ja: ["Aよりすぐれている"], phrase: "be superior to others" },
    { id: 289, part: 1, pos: "a", star: 3, en: "efficient", ja: ["効率がいい"], phrase: "an efficient method" },
    { id: 290, part: 1, pos: "a", star: 3, en: "fundamental", ja: ["基本的な"], phrase: "fundamental rights" },
    { id: 291, part: 1, pos: "a", star: 2, en: "narrow", ja: ["狭い"], phrase: "a narrow road" },
    { id: 292, part: 1, pos: "a", star: 3, en: "reasonable", ja: ["理にかなった"], phrase: "a reasonable price" },
    { id: 293, part: 1, pos: "a", star: 2, en: "nervous", ja: ["神経質な", "不安な"], phrase: "get nervous" },
    { id: 294, part: 1, pos: "a", star: 2, en: "alike", ja: ["似ている"], phrase: "look alike" },
    { id: 295, part: 1, pos: "a", star: 3, en: "domestic", ja: ["家庭の", "国内の"], phrase: "domestic violence" },
    { id: 296, part: 1, pos: "a", star: 2, en: "negative", ja: ["否定の"], phrase: "a negative answer" },
    { id: 297, part: 1, pos: "a", star: 3, en: "moral", ja: ["道徳的な"], phrase: "moral standards" },
    { id: 298, part: 1, pos: "a", star: 2, en: "eager", hint: "to do", ja: ["～することを熱望している"], phrase: "be eager to learn" },
    { id: 299, part: 1, pos: "a", star: 3, en: "remarkable", ja: ["すばらしい"], phrase: "a remarkable progress" },
    { id: 300, part: 1, pos: "a", star: 2, en: "evil", ja: ["悪い"], phrase: "an evil spirit" },
    { id: 301, part: 1, pos: "a", star: 2, en: "awake", ja: ["目を覚まして"], phrase: "be wide awake" },
    { id: 302, part: 1, pos: "a", star: 1, en: "aged", ja: ["年老いた"], phrase: "aged 18 and over" },
    { id: 303, part: 1, pos: "a", star: 3, en: "anxious", ja: ["心配して", "切望して"], phrase: "be anxious about the future" },
    { id: 304, part: 1, pos: "a", star: 2, en: "tough", ja: ["たくましい", "骨の折れる"], phrase: "a tough guy" },
    { id: 305, part: 1, pos: "a", star: 3, en: "nuclear", ja: ["核の", "原子力の"], phrase: "nuclear weapons" },
    { id: 306, part: 1, pos: "a", star: 3, en: "legal", ja: ["合法の", "法律の"], phrase: "legal action" },
    { id: 307, part: 1, pos: "a", star: 2, en: "curious", ja: ["好奇心の強い"], phrase: "be curious about everything" },
    { id: 308, part: 1, pos: "a", star: 3, en: "civil", ja: ["一般市民の"], phrase: "civil rights" },
    { id: 309, part: 1, pos: "a", star: 3, en: "recent", ja: ["最近の"], phrase: "a recent study" },
    { id: 310, part: 1, pos: "a", star: 2, en: "senior", ja: ["上級の", "先輩の"], phrase: "senior citizens" },
    { id: 311, part: 1, pos: "a", star: 2, en: "afterward", ja: ["その後"], phrase: "shortly afterward" },
    { id: 312, part: 1, pos: "a", star: 3, en: "nearly", ja: ["ほとんど"], phrase: "nearly 100 people" },
    { id: 313, part: 1, pos: "a", star: 3, en: "therefore", ja: ["それゆえに"], phrase: "therefore, it is true" },
    { id: 314, part: 1, pos: "a", star: 3, en: "exactly", ja: ["正確に"], phrase: "exactly the same" },
    { id: 315, part: 1, pos: "a", star: 2, en: "possibly", ja: ["ひょっとすると", "どうしてもVできない"], phrase: "cannot possibly do" },
    { id: 316, part: 1, pos: "n", star: 3, en: "contrary", ja: ["反対に"], phrase: "on the contrary" },
    { id: 317, part: 1, pos: "a", star: 2, en: "occasionally", ja: ["時々"], phrase: "occasionally visit" },
    { id: 318, part: 1, pos: "a", star: 2, en: "somehow", ja: ["どういうわけか", "なぜか"], phrase: "somehow or other" },
    { id: 319, part: 1, pos: "a", star: 2, en: "seldom", ja: ["めったに～ない"], phrase: "seldom see him" },
    { id: 320, part: 1, pos: "a", star: 3, en: "thus", ja: ["それゆえ", "そのように"], phrase: "thus, we conclude" },
    { id: 321, part: 1, pos: "n", star: 2, en: "throughout", ja: ["いたる所に"], phrase: "throughout the world" },
    { id: 322, part: 1, pos: "n", star: 2, en: "unlike", ja: ["～と違って"], phrase: "unlike his brother" },
    { id: 323, part: 1, pos: "n", star: 2, en: "besides", ja: ["～に加えて"], phrase: "besides English" },
    { id: 324, part: 1, pos: "n", star: 3, en: "beyond", ja: ["～の向こうに", "～できる範囲をこえて"], phrase: "beyond description" },
    { id: 325, part: 1, pos: "n", star: 3, en: "within", ja: ["～以内で"], phrase: "within a mile" },
    { id: 326, part: 1, pos: "n", star: 2, en: "nor", hint: "neither A nor B", ja: ["～もない"], phrase: "neither A nor B" },
    { id: 327, part: 1, pos: "n", star: 3, en: "unless", ja: ["～しない限り"], phrase: "unless it rains" },
    { id: 328, part: 1, pos: "n", star: 2, en: "except", ja: ["～を除いて"], phrase: "except for him" },
    { id: 329, part: 1, pos: "v", star: 2, en: "ought", ja: ["～すべきである"], phrase: "ought to go" },
    { id: 330, part: 1, pos: "n", star: 3, en: "in spite of", ja: ["～にもかかわらず"], phrase: "in spite of the rain" },
    { id: 331, part: 1, pos: "n", star: 3, en: "whether", ja: ["～かどうか", "～であろうとなかろうと"], phrase: "whether it is true or not" },
    { id: 332, part: 1, pos: "v", star: 3, en: "explain", ja: ["～を説明する"], phrase: "explain the reason" },
    { id: 333, part: 1, pos: "v", star: 3, en: "accept", ja: ["～を受け入れる"], phrase: "accept the offer" },
    { id: 334, part: 1, pos: "v", star: 3, en: "produce", ja: ["～を生産する"], phrase: "produce cars" },
    { id: 335, part: 1, pos: "v", star: 3, en: "exist", ja: ["存在する"], phrase: "exist in nature" },
    { id: 336, part: 1, pos: "v", star: 3, en: "express", ja: ["～を表現する"], phrase: "express one's feelings" },
    { id: 337, part: 1, pos: "v", star: 3, en: "add", hint: "A to B", ja: ["～を加える"], phrase: "add A to B" },
    { id: 338, part: 1, pos: "v", star: 3, en: "avoid", ja: ["～を避ける"], phrase: "avoid making mistakes" },
    { id: 339, part: 1, pos: "v", star: 3, en: "marry", ja: ["～と結婚する"], phrase: "marry him" },
    { id: 340, part: 1, pos: "v", star: 3, en: "protect", ja: ["～を守る"], phrase: "protect nature" },
    { id: 341, part: 1, pos: "v", star: 3, en: "affect", ja: ["～に影響する"], phrase: "affect the result" },
    { id: 342, part: 1, pos: "v", star: 3, en: "determine", ja: ["～を決定する"], phrase: "determine the future" },
    { id: 343, part: 1, pos: "v", star: 3, en: "solve", ja: ["～を解決する"], phrase: "solve the problem" },
    { id: 344, part: 1, pos: "v", star: 3, en: "contain", ja: ["～を含んでいる"], phrase: "contain vitamins" },
    { id: 345, part: 1, pos: "v", star: 3, en: "discuss", ja: ["～を議論する"], phrase: "discuss the matter" },
    { id: 346, part: 1, pos: "v", star: 3, en: "ignore", ja: ["～を無視する"], phrase: "ignore his advice" },
    { id: 347, part: 1, pos: "v", star: 2, en: "guess", ja: ["～を推測する"], phrase: "guess what it is" },
    { id: 348, part: 1, pos: "v", star: 2, en: "exchange", hint: "A for B", ja: ["交換する"], phrase: "exchange A for B" },
    { id: 349, part: 1, pos: "v", star: 3, en: "satisfy", ja: ["～を満たす"], phrase: "satisfy his needs" },
    { id: 350, part: 1, pos: "v", star: 2, en: "complain", ja: ["苦情を言う"], phrase: "complain about the noise" },
    { id: 351, part: 1, pos: "v", star: 3, en: "achieve", ja: ["～を達成する"], phrase: "achieve the goal" },
    { id: 352, part: 1, pos: "v", star: 3, en: "enable", ja: ["～を可能にする"], phrase: "enable him to do" },
    { id: 353, part: 1, pos: "v", star: 3, en: "intend", ja: ["つもりだ"], phrase: "intend to stay" },
    { id: 354, part: 1, pos: "v", star: 3, en: "obtain", ja: ["～を得る"], phrase: "obtain information" },
    { id: 355, part: 1, pos: "v", star: 2, en: "divide", hint: "A into B", ja: ["分割する"], phrase: "divide A into B" },
    { id: 356, part: 1, pos: "v", star: 2, en: "annoy", ja: ["～をいらいらさせる"], phrase: "annoy people" },
    { id: 357, part: 1, pos: "v", star: 2, en: "differ", ja: ["異なる"], phrase: "differ from each other" },
    { id: 358, part: 1, pos: "v", star: 2, en: "educate", ja: ["～を教育する"], phrase: "educate children" },
    { id: 359, part: 1, pos: "v", star: 2, en: "borrow", ja: ["～を借りる"], phrase: "borrow a book" },
    { id: 360, part: 1, pos: "v", star: 2, en: "invent", ja: ["～を発明する"], phrase: "invent a machine" },
    { id: 361, part: 1, pos: "v", star: 3, en: "promote", ja: ["～を促進する"], phrase: "promote health" },
    { id: 362, part: 1, pos: "v", star: 3, en: "advise", ja: ["～に忠告する"], phrase: "advise him to stop" },
    { id: 363, part: 1, pos: "v", star: 2, en: "retire", ja: ["辞める"], phrase: "retire from work" },
    { id: 364, part: 1, pos: "v", star: 2, en: "permit", ja: ["～を許す"], phrase: "permit him to go" },
    { id: 365, part: 1, pos: "v", star: 3, en: "recommend", ja: ["～を勧める"], phrase: "recommend this book" },
    { id: 366, part: 1, pos: "v", star: 2, en: "apologize", ja: ["謝る"], phrase: "apologize for the delay" },
    { id: 367, part: 1, pos: "v", star: 3, en: "inform", hint: "A of B", ja: ["～に知らせる"], phrase: "inform A of B" },
    { id: 368, part: 1, pos: "v", star: 3, en: "oppose", ja: ["～に反対する"], phrase: "oppose the plan" },
    { id: 369, part: 1, pos: "v", star: 2, en: "trust", ja: ["～を信用する"], phrase: "trust him" },
    { id: 370, part: 1, pos: "v", star: 2, en: "select", ja: ["～を選ぶ"], phrase: "select the best" },
    { id: 371, part: 1, pos: "v", star: 2, en: "praise", ja: ["～をほめる"], phrase: "praise him for his work" },
    { id: 372, part: 1, pos: "v", star: 2, en: "handle", ja: ["～に対処する"], phrase: "handle the problem" },
    { id: 373, part: 1, pos: "v", star: 3, en: "propose", ja: ["～を提案する"], phrase: "propose a new plan" },
    { id: 374, part: 1, pos: "v", star: 2, en: "breathe", ja: ["～を呼吸する"], phrase: "breathe fresh air" },
    { id: 375, part: 1, pos: "v", star: 3, en: "criticize", ja: ["～を非難する"], phrase: "criticize the policy" },
    { id: 376, part: 1, pos: "v", star: 3, en: "overcome", ja: ["～に打ち勝つ"], phrase: "overcome difficulties" },
    { id: 377, part: 1, pos: "v", star: 3, en: "possess", ja: ["～を持っている"], phrase: "possess great power" },
    { id: 378, part: 1, pos: "v", star: 3, en: "predict", ja: ["～を予言する"], phrase: "predict the future" },
    { id: 379, part: 1, pos: "v", star: 3, en: "publish", ja: ["～を出版する"], phrase: "publish a book" },
    { id: 380, part: 1, pos: "a", star: 1, en: "floating", ja: ["浮かぶ"], phrase: "floating on the water" },
    { id: 381, part: 1, pos: "v", star: 3, en: "recall", ja: ["～を思い出す"], phrase: "recall the event" },
    { id: 382, part: 1, pos: "v", star: 3, en: "explore", ja: ["～を探検する"], phrase: "explore the universe" },
    { id: 383, part: 1, pos: "v", star: 3, en: "pretend", ja: ["ふりをする"], phrase: "pretend to be asleep" },
    { id: 384, part: 1, pos: "v", star: 3, en: "absorb", ja: ["～を吸収する"], phrase: "absorb water" },
    { id: 385, part: 1, pos: "v", star: 2, en: "resemble", ja: ["～に似ている"], phrase: "resemble his father" },
    { id: 386, part: 1, pos: "v", star: 2, en: "tear", ja: ["～を引き裂く"], phrase: "tear a letter" },
    { id: 387, part: 1, pos: "v", star: 3, en: "consume", ja: ["～を消費する"], phrase: "consume energy" },
    { id: 388, part: 1, pos: "v", star: 3, en: "compete", ja: ["競争する"], phrase: "compete with him" },
    { id: 389, part: 1, pos: "v", star: 2, en: "quit", ja: ["～をやめる"], phrase: "quit smoking" },
    { id: 390, part: 1, pos: "v", star: 3, en: "announce", ja: ["～を発表する"], phrase: "announce the news" },
    { id: 391, part: 1, pos: "v", star: 3, en: "react", ja: ["反応する"], phrase: "react to light" },
    { id: 392, part: 1, pos: "v", star: 2, en: "wander", ja: ["歩き回る"], phrase: "wander around the city" },
    { id: 393, part: 1, pos: "v", star: 1, en: "text", ja: ["メールを送る"], phrase: "text a friend" },
    { id: 394, part: 1, pos: "v", star: 3, en: "generate", ja: ["～を生み出す"], phrase: "generate electricity" },
    { id: 395, part: 1, pos: "v", star: 2, en: "score", ja: ["～を取る"], phrase: "score a goal" },
    { id: 396, part: 1, pos: "n", star: 3, en: "government", ja: ["政府"], phrase: "the Japanese government" },
    { id: 397, part: 1, pos: "n", star: 3, en: "knowledge", ja: ["知識"], phrase: "scientific knowledge" },
    { id: 398, part: 1, pos: "n", star: 3, en: "nation", ja: ["国"], phrase: "the Asian nations" },
    { id: 399, part: 1, pos: "n", star: 3, en: "effort", ja: ["努力"], phrase: "make an effort" },
    { id: 400, part: 1, pos: "n", star: 3, en: "period", ja: ["時代"], phrase: "a period of time" }
];
