    // 301-400
    { id: 301, part: 1, pos: "a", star: 2, en: "awake", ja: ["目を覚まして"], phrase: "be wide awake" },
    { id: 302, part: 1, pos: "a", star: 1, en: "aged", ja: ["年老いた"], phrase: "aged 18 and over" },
    { id: 303, part: 1, pos: "a", star: 3, en: "anxious", ja: ["心配して", "切望して"], phrase: "be anxious about the future" },
    { id: 304, part: 1, pos: "a", star: 2, en: "tough", ja: ["たくましい", "骨の折れる"], phrase: "a tough guy" },
    { id: 305, part: 1, pos: "a", star: 3, en: "nuclear", ja: ["核の", "原子力の"], phrase: "nuclear weapons" },
    { id: 306, part: 1, pos: "a", star: 3, en: "legal", ja: ["合法の", "法律の"], phrase: "legal action" },
    { id: 307, part: 1, pos: "a", star: 2, en: "curious", ja: ["好奇心の強い"], phrase: "be curious about everything" },
    { id: 308, part: 1, pos: "a", star: 3, en: "civil", ja: ["一般市民の"], phrase: "civil rights" },
    { id: 309, part: 1, pos: "a", star: 3, en: "recent", ja: ["最近の"], phrase: "a recent study" },
    { id: 310, part: 1, pos: "a", star: 2, en: "senior", ja: ["上級の", "先輩の"], phrase: "senior citizens" },
    { id: 311, part: 1, pos: "a", star: 2, en: "afterward", ja: ["その後"], phrase: "shortly afterward" },
    { id: 312, part: 1, pos: "a", star: 3, en: "nearly", ja: ["ほとんど"], phrase: "nearly 100 people" },
    { id: 313, part: 1, pos: "a", star: 3, en: "therefore", ja: ["それゆえに"], phrase: "therefore, it is true" },
    { id: 314, part: 1, pos: "a", star: 3, en: "exactly", ja: ["正確に"], phrase: "exactly the same" },
    { id: 315, part: 1, pos: "a", star: 2, en: "possibly", ja: ["ひょっとすると", "どうしてもVできない"], phrase: "cannot possibly do" },
    { id: 316, part: 1, pos: "n", star: 3, en: "contrary", ja: ["反対に"], phrase: "on the contrary" },
    { id: 317, part: 1, pos: "a", star: 2, en: "occasionally", ja: ["時々"], phrase: "occasionally visit" },
    { id: 318, part: 1, pos: "a", star: 2, en: "somehow", ja: ["どういうわけか", "なぜか"], phrase: "somehow or other" },
    { id: 319, part: 1, pos: "a", star: 2, en: "seldom", ja: ["めったに～ない"], phrase: "seldom see him" },
    { id: 320, part: 1, pos: "a", star: 3, en: "thus", ja: ["それゆえ", "そのように"], phrase: "thus, we conclude" },
    { id: 321, part: 1, pos: "n", star: 2, en: "throughout", ja: ["いたる所に"], phrase: "throughout the world" },
    { id: 322, part: 1, pos: "n", star: 2, en: "unlike", ja: ["～と違って"], phrase: "unlike his brother" },
    { id: 323, part: 1, pos: "n", star: 2, en: "besides", ja: ["～に加えて"], phrase: "besides English" },
    { id: 324, part: 1, pos: "n", star: 3, en: "beyond", ja: ["～の向こうに", "～できる範囲をこえて"], phrase: "beyond description" },
    { id: 325, part: 1, pos: "n", star: 3, en: "within", ja: ["～以内で"], phrase: "within a mile" },
    { id: 326, part: 1, pos: "n", star: 2, en: "nor", hint: "neither A nor B", ja: ["～もない"], phrase: "neither A nor B" },
    { id: 327, part: 1, pos: "n", star: 3, en: "unless", ja: ["～しない限り"], phrase: "unless it rains" },
    { id: 328, part: 1, pos: "n", star: 2, en: "except", ja: ["～を除いて"], phrase: "except for him" },
    { id: 329, part: 1, pos: "v", star: 2, en: "ought", ja: ["～すべきである"], phrase: "ought to go" },
    { id: 330, part: 1, pos: "n", star: 3, en: "in spite of", ja: ["～にもかかわらず"], phrase: "in spite of the rain" },
    { id: 331, part: 1, pos: "n", star: 3, en: "whether", ja: ["～かどうか", "～であろうとなかろうと"], phrase: "whether it is true or not" },
    { id: 332, part: 1, pos: "v", star: 3, en: "explain", ja: ["～を説明する"], phrase: "explain the reason" },
    { id: 333, part: 1, pos: "v", star: 3, en: "accept", ja: ["～を受け入れる"], phrase: "accept the offer" },
    { id: 334, part: 1, pos: "v", star: 3, en: "produce", ja: ["～を生産する"], phrase: "produce cars" },
    { id: 335, part: 1, pos: "v", star: 3, en: "exist", ja: ["存在する"], phrase: "exist in nature" },
    { id: 336, part: 1, pos: "v", star: 3, en: "express", ja: ["～を表現する"], phrase: "express one's feelings" },
    { id: 337, part: 1, pos: "v", star: 3, en: "add", hint: "A to B", ja: ["～を加える"], phrase: "add A to B" },
    { id: 338, part: 1, pos: "v", star: 3, en: "avoid", ja: ["～を避ける"], phrase: "avoid making mistakes" },
    { id: 339, part: 1, pos: "v", star: 3, en: "marry", ja: ["～と結婚する"], phrase: "marry him" },
    { id: 340, part: 1, pos: "v", star: 3, en: "protect", ja: ["～を守る"], phrase: "protect nature" },
    { id: 341, part: 1, pos: "v", star: 3, en: "affect", ja: ["～に影響する"], phrase: "affect the result" },
    { id: 342, part: 1, pos: "v", star: 3, en: "determine", ja: ["～を決定する"], phrase: "determine the future" },
    { id: 343, part: 1, pos: "v", star: 3, en: "solve", ja: ["～を解決する"], phrase: "solve the problem" },
    { id: 344, part: 1, pos: "v", star: 3, en: "contain", ja: ["～を含んでいる"], phrase: "contain vitamins" },
    { id: 345, part: 1, pos: "v", star: 3, en: "discuss", ja: ["～を議論する"], phrase: "discuss the matter" },
    { id: 346, part: 1, pos: "v", star: 3, en: "ignore", ja: ["～を無視する"], phrase: "ignore his advice" },
    { id: 347, part: 1, pos: "v", star: 2, en: "guess", ja: ["～を推測する"], phrase: "guess what it is" },
    { id: 348, part: 1, pos: "v", star: 2, en: "exchange", hint: "A for B", ja: ["交換する"], phrase: "exchange A for B" },
    { id: 349, part: 1, pos: "v", star: 3, en: "satisfy", ja: ["～を満たす"], phrase: "satisfy his needs" },
    { id: 350, part: 1, pos: "v", star: 2, en: "complain", ja: ["苦情を言う"], phrase: "complain about the noise" },
    { id: 351, part: 1, pos: "v", star: 3, en: "achieve", ja: ["～を達成する"], phrase: "achieve the goal" },
    { id: 352, part: 1, pos: "v", star: 3, en: "enable", ja: ["～を可能にする"], phrase: "enable him to do" },
    { id: 353, part: 1, pos: "v", star: 3, en: "intend", ja: ["つもりだ"], phrase: "intend to stay" },
    { id: 354, part: 1, pos: "v", star: 3, en: "obtain", ja: ["～を得る"], phrase: "obtain information" },
    { id: 355, part: 1, pos: "v", star: 2, en: "divide", hint: "A into B", ja: ["分割する"], phrase: "divide A into B" },
    { id: 356, part: 1, pos: "v", star: 2, en: "annoy", ja: ["～をいらいらさせる"], phrase: "annoy people" },
    { id: 357, part: 1, pos: "v", star: 2, en: "differ", ja: ["異なる"], phrase: "differ from each other" },
    { id: 358, part: 1, pos: "v", star: 2, en: "educate", ja: ["～を教育する"], phrase: "educate children" },
    { id: 359, part: 1, pos: "v", star: 2, en: "borrow", ja: ["～を借りる"], phrase: "borrow a book" },
    { id: 360, part: 1, pos: "v", star: 2, en: "invent", ja: ["～を発明する"], phrase: "invent a machine" },
    { id: 361, part: 1, pos: "v", star: 3, en: "promote", ja: ["～を促進する"], phrase: "promote health" },
    { id: 362, part: 1, pos: "v", star: 3, en: "advise", ja: ["～に忠告する"], phrase: "advise him to stop" },
    { id: 363, part: 1, pos: "v", star: 2, en: "retire", ja: ["辞める"], phrase: "retire from work" },
    { id: 364, part: 1, pos: "v", star: 2, en: "permit", ja: ["～を許す"], phrase: "permit him to go" },
    { id: 365, part: 1, pos: "v", star: 3, en: "recommend", ja: ["～を勧める"], phrase: "recommend this book" },
    { id: 366, part: 1, pos: "v", star: 2, en: "apologize", ja: ["謝る"], phrase: "apologize for the delay" },
    { id: 367, part: 1, pos: "v", star: 3, en: "inform", hint: "A of B", ja: ["～に知らせる"], phrase: "inform A of B" },
    { id: 368, part: 1, pos: "v", star: 3, en: "oppose", ja: ["～に反対する"], phrase: "oppose the plan" },
    { id: 369, part: 1, pos: "v", star: 2, en: "trust", ja: ["～を信用する"], phrase: "trust him" },
    { id: 370, part: 1, pos: "v", star: 2, en: "select", ja: ["～を選ぶ"], phrase: "select the best" },
    { id: 371, part: 1, pos: "v", star: 2, en: "praise", ja: ["～をほめる"], phrase: "praise him for his work" },
    { id: 372, part: 1, pos: "v", star: 2, en: "handle", ja: ["～に対処する"], phrase: "handle the problem" },
    { id: 373, part: 1, pos: "v", star: 3, en: "propose", ja: ["～を提案する"], phrase: "propose a new plan" },
    { id: 374, part: 1, pos: "v", star: 2, en: "breathe", ja: ["～を呼吸する"], phrase: "breathe fresh air" },
    { id: 375, part: 1, pos: "v", star: 3, en: "criticize", ja: ["～を非難する"], phrase: "criticize the policy" },
    { id: 376, part: 1, pos: "v", star: 3, en: "overcome", ja: ["～に打ち勝つ"], phrase: "overcome difficulties" },
    { id: 377, part: 1, pos: "v", star: 3, en: "possess", ja: ["～を持っている"], phrase: "possess great power" },
    { id: 378, part: 1, pos: "v", star: 3, en: "predict", ja: ["～を予言する"], phrase: "predict the future" },
    { id: 379, part: 1, pos: "v", star: 3, en: "publish", ja: ["～を出版する"], phrase: "publish a book" },
    { id: 380, part: 1, pos: "a", star: 1, en: "floating", ja: ["浮かぶ"], phrase: "floating on the water" },
    { id: 381, part: 1, pos: "v", star: 3, en: "recall", ja: ["～を思い出す"], phrase: "recall the event" },
    { id: 382, part: 1, pos: "v", star: 3, en: "explore", ja: ["～を探検する"], phrase: "explore the universe" },
    { id: 383, part: 1, pos: "v", star: 3, en: "pretend", ja: ["ふりをする"], phrase: "pretend to be asleep" },
    { id: 384, part: 1, pos: "v", star: 3, en: "absorb", ja: ["～を吸収する"], phrase: "absorb water" },
    { id: 385, part: 1, pos: "v", star: 2, en: "resemble", ja: ["～に似ている"], phrase: "resemble his father" },
    { id: 386, part: 1, pos: "v", star: 2, en: "tear", ja: ["～を引き裂く"], phrase: "tear a letter" },
    { id: 387, part: 1, pos: "v", star: 3, en: "consume", ja: ["～を消費する"], phrase: "consume energy" },
    { id: 388, part: 1, pos: "v", star: 3, en: "compete", ja: ["競争する"], phrase: "compete with him" },
    { id: 389, part: 1, pos: "v", star: 2, en: "quit", ja: ["～をやめる"], phrase: "quit smoking" },
    { id: 390, part: 1, pos: "v", star: 3, en: "announce", ja: ["～を発表する"], phrase: "announce the news" },
    { id: 391, part: 1, pos: "v", star: 3, en: "react", ja: ["反応する"], phrase: "react to light" },
    { id: 392, part: 1, pos: "v", star: 2, en: "wander", ja: ["歩き回る"], phrase: "wander around the city" },
    { id: 393, part: 1, pos: "v", star: 1, en: "text", ja: ["メールを送る"], phrase: "text a friend" },
    { id: 394, part: 1, pos: "v", star: 3, en: "generate", ja: ["～を生み出す"], phrase: "generate electricity" },
    { id: 395, part: 1, pos: "v", star: 2, en: "score", ja: ["～を取る"], phrase: "score a goal" },
    { id: 396, part: 1, pos: "n", star: 3, en: "government", ja: ["政府"], phrase: "the Japanese government" },
    { id: 397, part: 1, pos: "n", star: 3, en: "knowledge", ja: ["知識"], phrase: "scientific knowledge" },
    { id: 398, part: 1, pos: "n", star: 3, en: "nation", ja: ["国"], phrase: "the Asian nations" },
    { id: 399, part: 1, pos: "n", star: 3, en: "effort", ja: ["努力"], phrase: "make an effort" },
    { id: 400, part: 1, pos: "n", star: 3, en: "period", ja: ["時代"], phrase: "a period of time" }
